apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert-clusterissuer
  namespace: app
spec:
  secretName: app-cert-clusterissuer-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt-prod
  dnsNames:
  - app2.singorojo.my.id